name = "Bar Contact Simulation"
dof = 3
OUTPUT = "temp/bar_contact.json.xz"


[[sim]]
name = "BAR Simulation"
dof = 3

[[sim.meshes]]
file = "meshes/bar_block.inp"
volumes = ["bar_body" , "block_body"]

[[sim.boundary_conditions]]
type = "fixed"
name = "free_end"
values = [0.05, 0, false]

[[sim.boundary_conditions]]
type = "fixed"
name = "fixed_end"
values = [0, 0.05, false]

[sim.output]
file = "examples/output/bar_contact/bar_contact.bin.xz"
vtk = "examples/output/bar_contact/bar_contact.vtk"
clear_directory = true

[sim.solver]
extra_stiffness = 1e13
method = "explicit"
# time_step = 0.000001
time_steps = 1000
vtk_save_steps = 1000