name = "Circle Pull Simulation"
dof = 3
OUTPUT = "temp/circle_pull.json.xz"


[[sim]]
mesh = "meshes/circle_pull.inp"

[[sim.boundary_conditions]]
type = "fixed"
name = "side1"
values = [0.05, 0, false]

[[sim.boundary_conditions]]
type = "fixed"
name = "side2"
values = [0, 0.05, false]

[[sim.boundary_conditions]]
type = "fixed"
name = "top"
values = [false, false, 0]

[sim.output]
file = "examples/output/circle_pull/circle_pull.bin.xz"
vtk = "examples/output/circle_pull/circle_pull.vtk"
clear_directory = true

[sim.solver]
extra_stiffness = 1e13
method = "explicit"
# time_step = 0.000001
time_steps = 20000
vtk_save_steps = 500