name = "Bar Contact Simulation"
dof = 3
OUTPUT = "temp/hertz_contact.json.xz"


[[sim]]
name = "BAR Simulation"
dof = 3

[[sim.meshes]]
file = "meshes/hertz.inp"
volumes = ["cylinder" , "block"]
active_volumes = ["cylinder"]

[[sim.boundary_conditions]]
type = "fixed"
name = "top"
values = [ false, 0.0, false]

[[sim.boundary_conditions]]
type = "fixed"
name = "back_line"
values = [ false, false, 0.0]

[[sim.boundary_conditions]]
type = "load"
name = "top"
values = [-1000000, 0.0, 0.0]

[[sim.boundary_conditions]]
type = "fixed"
name = "block"
values = [0.0, 0.0, 0.0]


[[sim.boundary_conditions]]
type = "contact"
name = "contact_a"
secondary = "contact_b"


[sim.output]
file = "examples/output/hertz_contact/hertz_contact.bin.xz"
vtk = "examples/output/hertz_contact/hertz_contact.vtk"
clear_directory = true

[sim.solver]
extra_stiffness = 1e13
method = "explicit"
time_step = 0.0000001
time_steps = 20000
vtk_save_steps = 10000

#How To Run
#cargo run --bin read_input -- examples/hertz_contact.toml -v