name = "Bar Contact Simulation"
dof = 3
OUTPUT = "temp/hertz_contact.json.xz"


[[sim]]
name = "BAR Simulation"
dof = 3

[[sim.meshes]]
file = "meshes/hertz.inp"
volumes = ["cylinder" , "block"]
active_volumes = ["cylinder", "block"]

[[sim.boundary_conditions]]
type = "fixed"
name = "top"
values = [-0.002, 0.0, 0.0]

[[sim.boundary_conditions]]
type = "fixed"
name = "contact_a"
values = [0.0, 0.0, 0.0]


[[sim.boundary_conditions]]
type = "fixed"
name = "bottom"
values = [0.0, 0.0, 0.0]


# [[sim.boundary_conditions]]
# type = "contact"
# name = "contact_a"
# secondary = "contact_b"


[sim.output]
file = "examples/output/hertz_contact/hertz_contact.bin.xz"
vtk = "examples/output/hertz_contact/hertz_contact.vtk"
clear_directory = true

[sim.solver]
extra_stiffness = 1e13
method = "explicit"
# time_step = 0.000001
time_steps = 150000
vtk_save_steps = 5000