name = "Tube Simulation Project"
output = "examples/output/tube.json.xz"

[[sim]]
name = "BAR Simulation"
dof = 3

[[sim.meshes]]
file = "meshes/example_tube.inp.xz"
name= "tube_body"

[sim.output]
vtk = "examples/output/tube/tube_direct.vtk"

[[sim.boundary_conditions]]
type = "load"
name = "end1"
values = [20000, 20000, 0]

[[sim.boundary_conditions]]
type = "fixed"
name = "end2"
values = [0, 0, 0]

[[sim.materials]]
id = 1
youngs_modulus = 200000
poissons_ratio = 0.3


[[sim]]
name = "BAR Simulation 2"
mesh = "meshes/example_tube.inp.xz"
dof = 3

[sim.solver]
method = "explicit"
# time_step = 0.000011
time_steps = 10000
vtk_save_steps = 1000

[sim.output]
vtk = "examples/output/tube/tube_explicit.vtk"
clear_directory = true

[[sim.boundary_conditions]]
type = "load"
name = "end1"
values = [20000, 20000, 0]

[[sim.boundary_conditions]]
type = "fixed"
name = "end2"
values = [0, 0, 0]
