use std::io::{Write, BufWriter};
use crate::simulation::Simulation;
use crate::elements::{BrickElement, BaseElement, ElementType};
use std::collections::HashMap;

#[cfg(feature = "native")]
use hdf5_writer::{DatasetBuilder, Hdf5Builder, Hdf5Writer, WriteOptions, AttributeBuilder};
use nalgebra::Vector3;

//logging
use log::{info, debug, trace};



/// Write VTK file for visualization
pub fn write_vtk(filename: &str, simulation: &Simulation) -> std::io::Result<()> {
    info!("Writing VTK file: {}", filename);

    let file = std::fs::File::create(filename)?;
    let mut file = BufWriter::new(file);

    // Write VTK header
    file.write_all(b"# vtk DataFile Version 2.0\nGenerated by Rust\nASCII\nDATASET UNSTRUCTURED_GRID\n")?;

    let nodes = simulation.nodes();
    // Write points (nodes)
    writeln!(file, "POINTS {} float", nodes.len())?;
    for node in nodes.iter() {
        writeln!(file, "{} {} {}", node.position.x, node.position.y, node.position.z)?;
    }

    let all_elements: &HashMap<usize, Box<dyn BaseElement>> = simulation.elements();
    let elements: Vec<&Box<dyn BaseElement>> = all_elements.iter().filter(|(_id, element)| element.type_name() == ElementType::Brick).map(|(_, element)| element).collect();

    let elements_size = elements.len();    // Write cells (elements)
    let total_list_entries = elements_size * 9; // 8 nodes per element + 1 value for the number of points in the cell
    writeln!(file, "CELLS {} {}", elements_size, total_list_entries)?;
    for elem in elements.iter() {
        if !elem.is_active() {
            continue;
        }
        file.write_all(b"8 ")?; // 8-node brick element
        for &id in elem.get_connectivity() {
            write!(file, "{} ", id)?; // VTK uses 0-based index
        }
        file.write_all(b"\n")?;
    }

    // Write cell types (12 for hexahedron in VTK)
    writeln!(file, "CELL_TYPES {}", elements_size)?;
    for _ in 0..elements_size {
        file.write_all(b"12\n")?;
    }

    // Write point data for nodal displacements
    writeln!(file, "POINT_DATA {}", nodes.len())?;
    writeln!(file, "VECTORS displacement float")?;
    for node in nodes.iter() {
        writeln!(file, "{} {} {}", node.displacement.x, node.displacement.y, node.displacement.z)?;
    }

    // Write boundary condition forces as vector field
    let load_vector = simulation.get_global_force();
    writeln!(file, "VECTORS force float")?;
    for node_id in 0..nodes.len() {
        let fx = if node_id * 3 < load_vector.len() { load_vector[node_id * 3] } else { 0.0 };
        let fy = if node_id * 3 + 1 < load_vector.len() { load_vector[node_id * 3 + 1] } else { 0.0 };
        let fz = if node_id * 3 + 2 < load_vector.len() { load_vector[node_id * 3 + 2] } else { 0.0 };
        writeln!(file, "{} {} {}", fx, fy, fz)?;
    }

    // Write force magnitude as scalar field
    writeln!(file, "SCALARS f_mag float")?;
    writeln!(file, "LOOKUP_TABLE default")?;
    for node_id in 0..nodes.len() {
        let fx = if node_id * 3 < load_vector.len() { load_vector[node_id * 3] } else { 0.0 };
        let fy = if node_id * 3 + 1 < load_vector.len() { load_vector[node_id * 3 + 1] } else { 0.0 };
        let fz = if node_id * 3 + 2 < load_vector.len() { load_vector[node_id * 3 + 2] } else { 0.0 };
        let f_mag = (fx * fx + fy * fy + fz * fz).sqrt();
        writeln!(file, "{}", f_mag)?;
    }

    // Write node_fields as scalar data
    let node_fields = &simulation.node_fields;
    for (name, field) in node_fields.iter() {
        writeln!(file, "SCALARS {} float", name)?;
        writeln!(file, "LOOKUP_TABLE default")?;
        for value in field.iter() {
            writeln!(file, "{}", value)?;
        }
    }
    Ok(())
}


/// Write VTKHDF file (pure Rust, no C library)
/// Only available on native builds (requires hdf5-writer)
#[cfg(feature = "native")]
pub fn write_vtkhdf(filename: &str, simulation: &Simulation) -> std::io::Result<()> {
    println!("Writing VTKHDF file: {}", filename);

    let nodes = simulation.nodes();
    let n_points = nodes.len() as u64;

    // Collect elements (filter to Brick elements)
    let all_elements: &HashMap<usize, Box<dyn BaseElement>> = simulation.elements();
    let elements: Vec<&Box<dyn BaseElement>> = all_elements
        .iter()
        .filter(|(_id, element)| element.type_name() == ElementType::Brick)
        .map(|(_, element)| element)
        .collect();
    let n_elements = elements.len() as u64;

    // Build points data (flat array: x0,y0,z0, x1,y1,z1, ...)
    let mut points_data: Vec<f64> = Vec::with_capacity((n_points * 3) as usize);
    for node in nodes.iter() {
        points_data.push(node.position.x);
        points_data.push(node.position.y);
        points_data.push(node.position.z);
    }

    // Build connectivity data (flat array of node indices)
    let mut connectivity_data: Vec<i64> = Vec::with_capacity((n_elements * 8) as usize);
    for elem in elements.iter() {
        for &id in elem.get_connectivity() {
            connectivity_data.push(id as i64);
        }
    }

    // Build offsets (cumulative: 0, 8, 16, 24, ...)
    let offsets: Vec<i64> = (0..=n_elements).map(|i| (i * 8) as i64).collect();

    // Build types (12 = VTK_HEXAHEDRON for each element)
    let types: Vec<u8> = vec![12u8; n_elements as usize];

    // Build displacement data (flat array)
    let mut displacement_data: Vec<f64> = Vec::with_capacity((n_points * 3) as usize);
    for node in nodes.iter() {
        displacement_data.push(node.displacement.x);
        displacement_data.push(node.displacement.y);
        displacement_data.push(node.displacement.z);
    }

    // Build force data
    let load_vector = simulation.get_global_force();
    let mut force_data: Vec<f64> = Vec::with_capacity((n_points * 3) as usize);
    let mut f_mag: Vec<f64> = Vec::with_capacity(n_points as usize);
    
    for node_id in 0..(n_points as usize) {
        let fx = if node_id * 3 < load_vector.len() { load_vector[node_id * 3] } else { 0.0 };
        let fy = if node_id * 3 + 1 < load_vector.len() { load_vector[node_id * 3 + 1] } else { 0.0 };
        let fz = if node_id * 3 + 2 < load_vector.len() { load_vector[node_id * 3 + 2] } else { 0.0 };
        
        force_data.push(fx);
        force_data.push(fy);
        force_data.push(fz);
        f_mag.push((fx * fx + fy * fy + fz * fz).sqrt());
    }

    // Build HDF5 file using hdf5-writer
    let mut builder = Hdf5Builder::new();

    // Add VTKHDF group attributes
    // Type attribute: "UnstructuredGrid"
    builder = builder.group_attribute(
        "VTKHDF",
        AttributeBuilder::fixed_string("Type", "UnstructuredGrid")
    );
    
    // Version attribute: [2, 0]
    builder = builder.group_attribute(
        "VTKHDF",
        AttributeBuilder::vector("Version", &[2_i32, 0_i32])
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?
    );

    // VTKHDF/NumberOfPoints dataset
    builder = builder.dataset(
        DatasetBuilder::typed_data("VTKHDF/NumberOfPoints", vec![1_u64], &[n_points as i64])
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?
    );

    // VTKHDF/Points dataset (Nx3 stored as flat array)
    builder = builder.dataset(
        DatasetBuilder::typed_data("VTKHDF/Points", vec![n_points, 3_u64], &points_data)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?
    );

    // VTKHDF/NumberOfCells dataset
    builder = builder.dataset(
        DatasetBuilder::typed_data("VTKHDF/NumberOfCells", vec![1_u64], &[n_elements as i64])
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?
    );

    // VTKHDF/NumberOfConnectivityIds dataset
    builder = builder.dataset(
        DatasetBuilder::typed_data("VTKHDF/NumberOfConnectivityIds", vec![1_u64], &[(8 * n_elements) as i64])
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?
    );

    // VTKHDF/Connectivity dataset
    builder = builder.dataset(
        DatasetBuilder::typed_data("VTKHDF/Connectivity", vec![connectivity_data.len() as u64], &connectivity_data)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?
    );

    // VTKHDF/Offsets dataset
    builder = builder.dataset(
        DatasetBuilder::typed_data("VTKHDF/Offsets", vec![offsets.len() as u64], &offsets)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?
    );

    // VTKHDF/Types dataset
    builder = builder.dataset(
        DatasetBuilder::typed_data("VTKHDF/Types", vec![n_elements], &types)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?
    );

    // VTKHDF/PointData/Displacement dataset
    builder = builder.dataset(
        DatasetBuilder::typed_data("VTKHDF/PointData/Displacement", vec![n_points, 3_u64], &displacement_data)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?
    );

    // VTKHDF/PointData/force dataset
    builder = builder.dataset(
        DatasetBuilder::typed_data("VTKHDF/PointData/force", vec![n_points, 3_u64], &force_data)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?
    );

    // VTKHDF/PointData/f_mag dataset
    builder = builder.dataset(
        DatasetBuilder::typed_data("VTKHDF/PointData/f_mag", vec![n_points], &f_mag)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?
    );

    // Add node fields
    let node_fields = &simulation.node_fields;
    for (name, field) in node_fields.iter() {
        let path = format!("VTKHDF/PointData/{}", name);
        builder = builder.dataset(
            DatasetBuilder::typed_data(&path, vec![n_points], field)
                .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?
        );
    }

    // Build the write plan
    let plan = builder.into_plan()
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?;

    // Write to file
    let file = std::fs::File::create(filename)?;
    Hdf5Writer::new(file, WriteOptions::default())
        .finish(plan)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e.to_string()))?;

    Ok(())
}
